---
# This playbook will create vlans 10, 20, and 99 on all switches.

- hosts: switches
  gather_facts: false
  connection: local

  vars:
    cli:
      username: cisco
      password: cisco123!

    vlans:
      10: "Faculty"
      20: "Students"
      99: "Management"
    
  tasks:

    - name: create vlans
      ios_config:
        provider: "{{cli}}"
        lines:
          - name {{item.value}}
        parents:
          - vlan {{item.key}}
      with_dict: "{{vlans}}"
    
    - name: show vlan brief
      ios_command:
        provider: "{{cli}}"
        commands: show vlan brief
      
      register: vlan_brief

    - name: print output to screen
      debug:
        var=vlan_brief.stdout_lines


      